"""
Aesthetic category definitions for the Melody Map aesthetic engine.

Each category is grounded in:
- weighted genre ecosystem matches
- weighted artist ecosystem matches
- audio-feature targets
- era preferences
- discovery / popularity tendencies
- structural profile cues
"""

AESTHETIC_CATEGORIES = [
    {
        'id': 'shoegaze_haze',
        'label': 'Shoegaze Haze',
        'short_description': 'Blurred, reverb-soaked, luminous melancholy.',
        'genre_keywords': ['shoegaze', 'dream pop', 'slowcore', 'ambient pop', 'noise pop'],
        'artist_keywords': ['slowdive', 'my bloody valentine', 'cocteau twins', 'beach house', 'mazzy star'],
        'audio_targets': {
            'energy': 0.38,
            'valence': 0.36,
            'acousticness': 0.44,
            'instrumentalness': 0.25,
            'danceability': 0.32,
            'tempo': 94,
        },
        'audio_weights': {
            'energy': 1.0,
            'valence': 0.95,
            'acousticness': 0.8,
            'instrumentalness': 0.55,
            'danceability': 0.45,
            'tempo': 0.45,
        },
        'era_targets': {'1980s': 0.2, '1990s': 0.45, '2000s': 0.2, '2010s': 0.15},
        'discovery_target': 0.72,
        'diversity_target': 0.48,
        'texture_hints': ['hazy', 'grain-softened', 'diffused', 'velvet static'],
        'motion_hints': ['floating', 'slow drift', 'suspended', 'glimmering'],
        'palette_hints': ['indigo mist', 'lavender fog', 'deep periwinkle', 'moon-silver'],
        'visual_mood': ['luminous melancholy', 'blurred night air', 'soft distortion'],
        'cultural_descriptors': ['dream-pop adjacent', 'shoegaze scene', 'reverb culture'],
    },
    {
        'id': 'velvet_noir',
        'label': 'Velvet Noir',
        'short_description': 'Smoky elegance, low-gloss emotion, nocturnal sophistication.',
        'genre_keywords': ['jazz', 'trip hop', 'neo-soul', 'chamber pop', 'torch song'],
        'artist_keywords': ['sade', 'portishead', 'fiona apple', 'norah jones', 'chet baker'],
        'audio_targets': {
            'energy': 0.42,
            'valence': 0.32,
            'acousticness': 0.5,
            'instrumentalness': 0.22,
            'danceability': 0.46,
            'tempo': 92,
        },
        'audio_weights': {
            'energy': 0.8,
            'valence': 1.0,
            'acousticness': 0.75,
            'instrumentalness': 0.5,
            'danceability': 0.55,
            'tempo': 0.55,
        },
        'era_targets': {'1950s': 0.1, '1960s': 0.2, '1990s': 0.35, '2000s': 0.2, '2010s': 0.15},
        'discovery_target': 0.6,
        'diversity_target': 0.42,
        'texture_hints': ['velvet', 'smoke-lit', 'polished shadow', 'satin grain'],
        'motion_hints': ['slow sway', 'low flicker', 'glide', 'measured pulse'],
        'palette_hints': ['wine black', 'amber smoke', 'bronzed plum', 'midnight mahogany'],
        'visual_mood': ['candlelit restraint', 'smoky intimacy', 'dark elegance'],
        'cultural_descriptors': ['noir lounge', 'jazz-bar sophistication', 'midnight chamber-pop'],
    },
    {
        'id': 'glitch_angel',
        'label': 'Glitch Angel',
        'short_description': 'Digital sheen, emotional voltage, synthetic tenderness.',
        'genre_keywords': ['hyperpop', 'electropop', 'alt-pop', 'glitch', 'deconstructed club'],
        'artist_keywords': ['charli xcx', 'arca', 'sophie', 'caroline polachek', 'yeule'],
        'audio_targets': {
            'energy': 0.72,
            'valence': 0.52,
            'acousticness': 0.14,
            'instrumentalness': 0.12,
            'danceability': 0.7,
            'tempo': 128,
        },
        'audio_weights': {
            'energy': 0.9,
            'valence': 0.6,
            'acousticness': 0.9,
            'instrumentalness': 0.35,
            'danceability': 0.8,
            'tempo': 0.75,
        },
        'era_targets': {'2010s': 0.35, '2020s': 0.65},
        'discovery_target': 0.74,
        'diversity_target': 0.56,
        'texture_hints': ['chrome shimmer', 'pixel bloom', 'glass-static', 'digital lace'],
        'motion_hints': ['strobe flutter', 'nervous pulse', 'elastic pop', 'glitch drift'],
        'palette_hints': ['cyber pink', 'cold lilac', 'electric chrome', 'ice-blue neon'],
        'visual_mood': ['synthetic longing', 'angelic digitality', 'sharp-soft contrast'],
        'cultural_descriptors': ['hyperpop sphere', 'alt-electronic edge', 'post-internet gloss'],
    },
    {
        'id': 'pastoral_reverie',
        'label': 'Pastoral Reverie',
        'short_description': 'Earth-warm softness, acoustic light, handwritten intimacy.',
        'genre_keywords': ['folk', 'indie folk', 'singer-songwriter', 'americana', 'acoustic'],
        'artist_keywords': ['phoebe bridgers', 'adrianne lenker', 'bon iver', 'fleet foxes', 'joni mitchell'],
        'audio_targets': {
            'energy': 0.3,
            'valence': 0.5,
            'acousticness': 0.78,
            'instrumentalness': 0.16,
            'danceability': 0.28,
            'tempo': 88,
        },
        'audio_weights': {
            'energy': 0.75,
            'valence': 0.5,
            'acousticness': 1.0,
            'instrumentalness': 0.35,
            'danceability': 0.4,
            'tempo': 0.45,
        },
        'era_targets': {'1960s': 0.15, '1970s': 0.2, '2000s': 0.2, '2010s': 0.3, '2020s': 0.15},
        'discovery_target': 0.55,
        'diversity_target': 0.38,
        'texture_hints': ['linen-soft', 'pressed wildflowers', 'woodgrain', 'sun-faded paper'],
        'motion_hints': ['breeze', 'gentle sway', 'still warmth', 'slow unfurling'],
        'palette_hints': ['wheat gold', 'moss green', 'dusty cream', 'faded terracotta'],
        'visual_mood': ['handwritten tenderness', 'field-light calm', 'earthbound softness'],
        'cultural_descriptors': ['indie-folk intimacy', 'acoustic pastoralism', 'modern folk diary'],
    },
    {
        'id': 'analog_nostalgia',
        'label': 'Analog Nostalgia',
        'short_description': 'Film-grain warmth, memory glow, classic-rooted romance.',
        'genre_keywords': ['classic rock', 'soft rock', 'indie rock', 'folk rock', 'oldies'],
        'artist_keywords': ['fleetwood mac', 'the beatles', 'david bowie', 'the smiths', 'bruce springsteen'],
        'audio_targets': {
            'energy': 0.54,
            'valence': 0.54,
            'acousticness': 0.42,
            'instrumentalness': 0.12,
            'danceability': 0.5,
            'tempo': 112,
        },
        'audio_weights': {
            'energy': 0.55,
            'valence': 0.55,
            'acousticness': 0.6,
            'instrumentalness': 0.3,
            'danceability': 0.4,
            'tempo': 0.4,
        },
        'era_targets': {'1960s': 0.2, '1970s': 0.35, '1980s': 0.25, '1990s': 0.1, '2000s': 0.1},
        'discovery_target': 0.42,
        'diversity_target': 0.44,
        'texture_hints': ['film grain', 'sun-faded gloss', 'analog warmth', 'sepia paper'],
        'motion_hints': ['slow roll', 'memory dissolve', 'steady drive', 'warm orbit'],
        'palette_hints': ['burnished gold', 'aged brown', 'faded denim', 'autumn amber'],
        'visual_mood': ['memory-lit romance', 'analog warmth', 'time-softened color'],
        'cultural_descriptors': ['classic album culture', 'vinyl nostalgia', 'heritage-rock glow'],
    },
    {
        'id': 'post_punk_silhouette',
        'label': 'Post-Punk Silhouette',
        'short_description': 'Cool shadows, angular tension, urban nocturnal grace.',
        'genre_keywords': ['post-punk', 'darkwave', 'goth', 'new wave', 'coldwave'],
        'artist_keywords': ['joy division', 'the cure', 'siouxsie', 'depeche mode', 'molchat doma'],
        'audio_targets': {
            'energy': 0.58,
            'valence': 0.24,
            'acousticness': 0.18,
            'instrumentalness': 0.16,
            'danceability': 0.56,
            'tempo': 116,
        },
        'audio_weights': {
            'energy': 0.7,
            'valence': 1.0,
            'acousticness': 0.6,
            'instrumentalness': 0.35,
            'danceability': 0.65,
            'tempo': 0.55,
        },
        'era_targets': {'1980s': 0.45, '1990s': 0.2, '2000s': 0.1, '2010s': 0.15, '2020s': 0.1},
        'discovery_target': 0.68,
        'diversity_target': 0.4,
        'texture_hints': ['matte black', 'steel sheen', 'ink shadow', 'angular grain'],
        'motion_hints': ['cool pulse', 'measured stride', 'narrow beam', 'monochrome flicker'],
        'palette_hints': ['graphite', 'inky violet', 'smoked blue', 'ashen silver'],
        'visual_mood': ['urban nocturne', 'angular melancholy', 'cool theatrical shadow'],
        'cultural_descriptors': ['post-punk lineage', 'dark club silhouette', 'coldwave afterimage'],
    },
    {
        'id': 'celestial_romantic',
        'label': 'Celestial Romantic',
        'short_description': 'Soft emotional radiance with cosmic lift.',
        'genre_keywords': ['ambient', 'dream pop', 'art pop', 'baroque pop', 'indie pop'],
        'artist_keywords': ['weyes blood', 'fka twigs', 'lana del rey', 'mitski', 'cocteau twins'],
        'audio_targets': {
            'energy': 0.42,
            'valence': 0.58,
            'acousticness': 0.38,
            'instrumentalness': 0.12,
            'danceability': 0.4,
            'tempo': 98,
        },
        'audio_weights': {
            'energy': 0.6,
            'valence': 0.7,
            'acousticness': 0.55,
            'instrumentalness': 0.35,
            'danceability': 0.35,
            'tempo': 0.3,
        },
        'era_targets': {'1970s': 0.1, '2010s': 0.45, '2020s': 0.45},
        'discovery_target': 0.62,
        'diversity_target': 0.46,
        'texture_hints': ['pearl haze', 'stardust silk', 'luminous velvet', 'moonlit bloom'],
        'motion_hints': ['glow', 'levitation', 'soft orbit', 'slow bloom'],
        'palette_hints': ['rose-lilac', 'soft gold', 'opal blue', 'night plum'],
        'visual_mood': ['luminous tenderness', 'cosmic yearning', 'soft grandeur'],
        'cultural_descriptors': ['romantic art-pop', 'dream-lit celestiality', 'baroque-pop softness'],
    },
    {
        'id': 'electric_maximalist',
        'label': 'Electric Maximalist',
        'short_description': 'High-saturation movement, excess, and theatrical pop voltage.',
        'genre_keywords': ['dance pop', 'edm', 'electronic', 'house', 'pop'],
        'artist_keywords': ['lady gaga', 'dua lipa', 'robyn', 'charli xcx', 'rihanna'],
        'audio_targets': {
            'energy': 0.8,
            'valence': 0.62,
            'acousticness': 0.1,
            'instrumentalness': 0.05,
            'danceability': 0.8,
            'tempo': 126,
        },
        'audio_weights': {
            'energy': 1.0,
            'valence': 0.5,
            'acousticness': 0.7,
            'instrumentalness': 0.25,
            'danceability': 1.0,
            'tempo': 0.8,
        },
        'era_targets': {'2000s': 0.15, '2010s': 0.4, '2020s': 0.45},
        'discovery_target': 0.4,
        'diversity_target': 0.52,
        'texture_hints': ['lacquered gloss', 'laser color', 'reflective chrome', 'high-sheen glow'],
        'motion_hints': ['pulsing', 'strobe', 'surge', 'impact burst'],
        'palette_hints': ['hot magenta', 'electric cyan', 'acid lime', 'stage gold'],
        'visual_mood': ['theatrical charge', 'high-voltage joy', 'dance-floor glow'],
        'cultural_descriptors': ['club-pop maximalism', 'dance floor culture', 'neon spectacle'],
    },
    {
        'id': 'jazz_smoke',
        'label': 'Jazz Smoke',
        'short_description': 'Low-lit musicianship, amber shadow, quiet sophistication.',
        'genre_keywords': ['jazz', 'bebop', 'soul jazz', 'vocal jazz', 'blues'],
        'artist_keywords': ['miles davis', 'billie holiday', 'ella fitzgerald', 'chet baker', 'john coltrane'],
        'audio_targets': {
            'energy': 0.34,
            'valence': 0.34,
            'acousticness': 0.66,
            'instrumentalness': 0.45,
            'danceability': 0.36,
            'tempo': 90,
        },
        'audio_weights': {
            'energy': 0.5,
            'valence': 0.7,
            'acousticness': 0.8,
            'instrumentalness': 0.85,
            'danceability': 0.3,
            'tempo': 0.35,
        },
        'era_targets': {'1950s': 0.35, '1960s': 0.35, '1970s': 0.1, '1990s': 0.1, '2000s': 0.1},
        'discovery_target': 0.7,
        'diversity_target': 0.35,
        'texture_hints': ['cigarette smoke', 'amber glow', 'linen shadow', 'mahogany lacquer'],
        'motion_hints': ['late-night sway', 'soft swing', 'hushed drift', 'low ember pulse'],
        'palette_hints': ['amber brown', 'tarnished gold', 'oxblood', 'smoke gray'],
        'visual_mood': ['after-hours intimacy', 'smoky sophistication', 'quiet nocturne'],
        'cultural_descriptors': ['jazz-club lineage', 'vinyl room intimacy', 'torchlight noir'],
    },
    {
        'id': 'cinematic_dusk',
        'label': 'Cinematic Dusk',
        'short_description': 'Expansive, widescreen feeling with emotional horizon lines.',
        'genre_keywords': ['post-rock', 'cinematic', 'soundtrack', 'ambient', 'instrumental'],
        'artist_keywords': ['sigur ros', 'explosions in the sky', 'max richter', 'nils frahm', 'phoebe bridgers'],
        'audio_targets': {
            'energy': 0.4,
            'valence': 0.4,
            'acousticness': 0.42,
            'instrumentalness': 0.48,
            'danceability': 0.2,
            'tempo': 86,
        },
        'audio_weights': {
            'energy': 0.5,
            'valence': 0.5,
            'acousticness': 0.45,
            'instrumentalness': 0.9,
            'danceability': 0.3,
            'tempo': 0.35,
        },
        'era_targets': {'1990s': 0.2, '2000s': 0.3, '2010s': 0.35, '2020s': 0.15},
        'discovery_target': 0.66,
        'diversity_target': 0.43,
        'texture_hints': ['widescreen grain', 'dusky air', 'soft monumentality', 'mist horizon'],
        'motion_hints': ['slow ascent', 'expansion', 'long dissolve', 'horizon drift'],
        'palette_hints': ['storm blue', 'dust rose', 'fading violet', 'cloud silver'],
        'visual_mood': ['widescreen yearning', 'sunset aftermath', 'cinematic suspension'],
        'cultural_descriptors': ['soundtrack sensibility', 'post-rock horizon', 'ambient cinema'],
    },
    {
        'id': 'indie_diary',
        'label': 'Indie Diary',
        'short_description': 'Personal, handwritten, bittersweet, and observant.',
        'genre_keywords': ['indie rock', 'indie pop', 'bedroom pop', 'singer-songwriter', 'alt-pop'],
        'artist_keywords': ['mitski', 'clairo', 'beabadoobee', 'the 1975', 'phoebe bridgers'],
        'audio_targets': {
            'energy': 0.5,
            'valence': 0.46,
            'acousticness': 0.34,
            'instrumentalness': 0.08,
            'danceability': 0.5,
            'tempo': 104,
        },
        'audio_weights': {
            'energy': 0.45,
            'valence': 0.55,
            'acousticness': 0.4,
            'instrumentalness': 0.2,
            'danceability': 0.45,
            'tempo': 0.3,
        },
        'era_targets': {'2000s': 0.15, '2010s': 0.45, '2020s': 0.4},
        'discovery_target': 0.58,
        'diversity_target': 0.5,
        'texture_hints': ['paper-soft', 'bedroom glow', 'ink smudge', 'diary grain'],
        'motion_hints': ['page-turn', 'gentle jitter', 'soft skip', 'night-bus drift'],
        'palette_hints': ['dusty rose', 'cool beige', 'ink blue', 'soft plum'],
        'visual_mood': ['personal candor', 'bittersweet journaling', 'private glow'],
        'cultural_descriptors': ['bedroom-pop intimacy', 'indie diary energy', 'soft alt confessional'],
    },
]


DEFAULT_AESTHETIC_ID = 'indie_diary'
