export function buildDemoProfile() {
  const now = new Date().toISOString()

  return {
    provider: 'demo',
    generatedAt: now,
    syncedAt: now,
    userProfile: {
      name: 'Demo Listener',
      email: 'demo@melodymap.site',
      country: 'Signal',
      product: 'demo',
      followers: 1204,
      image: null,
    },
    topArtists: [
      { id: 'demo-artist-1', name: 'Beach House', genres: ['dream pop', 'indie pop'], popularity: 83, image: null, spotify_url: '#' },
      { id: 'demo-artist-2', name: 'Frank Ocean', genres: ['alternative r&b', 'neo soul'], popularity: 92, image: null, spotify_url: '#' },
      { id: 'demo-artist-3', name: 'Radiohead', genres: ['alternative rock', 'art rock'], popularity: 95, image: null, spotify_url: '#' },
      { id: 'demo-artist-4', name: 'FKA twigs', genres: ['art pop', 'electronic'], popularity: 79, image: null, spotify_url: '#' },
      { id: 'demo-artist-5', name: 'Slowdive', genres: ['shoegaze', 'dream pop'], popularity: 76, image: null, spotify_url: '#' },
      { id: 'demo-artist-6', name: 'James Blake', genres: ['electronic', 'alternative r&b'], popularity: 80, image: null, spotify_url: '#' },
    ],
    topTracks: [
      { id: 'demo-track-1', title: 'Space Song', artist: 'Beach House', album_art: null, spotify_url: '#' },
      { id: 'demo-track-2', title: 'Nights', artist: 'Frank Ocean', album_art: null, spotify_url: '#' },
      { id: 'demo-track-3', title: 'Reckoner', artist: 'Radiohead', album_art: null, spotify_url: '#' },
      { id: 'demo-track-4', title: 'Cellophane', artist: 'FKA twigs', album_art: null, spotify_url: '#' },
      { id: 'demo-track-5', title: 'Sugar for the Pill', artist: 'Slowdive', album_art: null, spotify_url: '#' },
      { id: 'demo-track-6', title: 'Retrograde', artist: 'James Blake', album_art: null, spotify_url: '#' },
    ],
    savedTracks: [],
    recentlyPlayed: [],
    genres: [
      { genre: 'dream pop', count: 4 },
      { genre: 'alternative r&b', count: 3 },
      { genre: 'art rock', count: 2 },
      { genre: 'shoegaze', count: 2 },
      { genre: 'electronic', count: 2 },
      { genre: 'indie pop', count: 1 },
    ],
    audioFeatures: {
      energy: 0.58,
      valence: 0.42,
      danceability: 0.51,
      acousticness: 0.28,
      tempo: 118,
    },
    analyticsMetrics: {
      energyScore: 58,
      valenceScore: 42,
      diversityScore: 74,
      nostalgiaIndex: 61,
      sonicBrightness: 54,
      tempoAvg: 118,
      mood: 'luminous introspection',
      emotionalProfile: 'cinematic, nocturnal, reflective',
      sampleSizes: {
        energyScore: 24,
        sonicBrightness: 24,
        nostalgiaIndex: 24,
      },
    },
    aestheticTags: ['ethereal', 'midnight glow', 'soft neon', 'sacred geometry'],
    personality: 'You move between nocturnal calm and emotionally charged revelation. Your taste seeks atmosphere first, but it stays grounded in memory and emotional precision.',
    mbti: {
      type: 'INFP',
      name: 'Nocturnal Dreamer',
    },
    confidence: {
      overall: 0.86,
      analytics: 0.83,
      identity: 0.88,
      galaxy: 0.82,
      soulmate: 0.76,
      labels: {
        overall: 'high',
        analytics: 'high',
        identity: 'high',
        galaxy: 'high',
        soulmate: 'medium',
      },
    },
    dataQuality: {
      provider: 'demo',
      topArtistsCount: 6,
      topTracksCount: 6,
      genresCount: 6,
      audioFeaturesRequested: 24,
      audioFeaturesCount: 24,
      audioCoverage: 1,
      hasAudioProfile: true,
      degradedReasons: [],
      sampleSizes: {
        energyScore: 24,
        sonicBrightness: 24,
        nostalgiaIndex: 24,
      },
      featureCoverageByMetric: {
        energyScore: 1,
        valenceScore: 1,
        diversityScore: 1,
      },
    },
    analyticsReadiness: {
      ready: true,
      confidence: { score: 0.83, label: 'high' },
      reasons: [],
    },
    identityReadiness: {
      ready: true,
      confidence: { score: 0.88, label: 'high' },
      mbtiReady: true,
      reasons: [],
    },
    soulmateReadiness: {
      ready: true,
      confidence: { score: 0.76, label: 'medium' },
      mode: 'demo',
      reasons: [],
    },
    isDemoProfile: true,
    canRenderGalaxy: true,
    canComputeAnalytics: true,
    canComputeIdentity: true,
  }
}
